### PR TITLE
Adds initial Terraform configuration to support Auth0

### PR DESCRIPTION
**Pull request by danielgrant**
This PR introduces the infrastructure resources to support the BFI IIIIF project, specifically:

- It utilises an S3 backend for the Terraform statefile.
- Configures the Auth0 tenants.
- Creates a couple of Auth0 client (one for testing, one for the platform).
- Creates an Auth0 connection - username and password only.
- Creates an Auth0 rule, which enriches responses from `/userinfo` with additional user metadata

### CODE REVIEW

**Comment by danielgrant** [comment]
Hi @stephenmcconnachie,

In terms of the password policy, I've taken the liberty of configuring the following:

- Auth0's `excellent` policy, which requires a mix of upper case, lower case, numbers and special characters.
- A minimum length of 12 characters.
- A password history of 5 (i.e. users, when changing passwords, cannot reuse the previous 5 passwords)
- A password dictionary consisting of the terms `bfi`, `british`, `film` and `institute`, meaning these terms cannot appear in a users password.
- Personal data blocking, meaning the users name, or the first part of their email address (i.e. before the `@`) cannot be used in their password.

Let me know if you want any changes to this.

The other part that I need some input on is the BFI logo. Auth0 expects this to be provided as an existing URL, and is recommended to be no greater than 150px height / width. Do you have a URL for this we can use? Currently I've taken the BFI logo and placed it into an S3 bucket hosted in Digirati's AWS estate, but this won't be suitable in the long term.

This PR doesn't contain the email configuration yet either, as we need the SMTP server in place for that.

**Comment by stephenmcconnachie** [comment]
> Hi @stephenmcconnachie,
> 
> In terms of the password policy, I've taken the liberty of configuring the following:
> 
> * Auth0's `excellent` policy, which requires a mix of upper case, lower case, numbers and special characters.
> * A minimum length of 12 characters.
> * A password history of 5 (i.e. users, when changing passwords, cannot reuse the previous 5 passwords)
> * A password dictionary consisting of the terms `bfi`, `british`, `film` and `institute`, meaning these terms cannot appear in a users password.
> * Personal data blocking, meaning the users name, or the first part of their email address (i.e. before the `@`) cannot be used in their password.
> 
> Let me know if you want any changes to this.
> 
> The other part that I need some input on is the BFI logo. Auth0 expects this to be provided as an existing URL, and is recommended to be no greater than 150px height / width. Do you have a URL for this we can use? Currently I've taken the BFI logo and placed it into an S3 bucket hosted in Digirati's AWS estate, but this won't be suitable in the long term.
> 
> This PR doesn't contain the email configuration yet either, as we need the SMTP server in place for that.

That all looks fine to me. @rwhscott could you consider it too, as we'll be creating users with pws upfront? (I _think_ the pw gets created upfront though we might be able to set a default with a 'must change' feature)

RE Logo - I'll ask my colleagues in Digital if there's an official AWS logo we can point to

RE SMTP: I created our account but it's waiting moderator approval so I'll set it up and test it once that's done

**Comment by danielgrant** [comment]
Thanks for the response @stephenmcconnachie, regarding this comment:

> I think the pw gets created upfront though we might be able to set a default with a 'must change' feature

Auth0 doesn't support forcing a password reset out-of-the-box. This is something that is theoretically possible but would require a good amount of custom work to implement and would require maintaining a flag on the users record, intercepting the login process, etc.

**Comment by danielgrant** [comment]
> Thanks for the response @stephenmcconnachie, regarding this comment:
> 
> > I think the pw gets created upfront though we might be able to set a default with a 'must change' feature
> 
> Auth0 doesn't support forcing a password reset out-of-the-box. This is something that is theoretically possible but would require a good amount of custom work to implement and would require maintaining a flag on the users record, intercepting the login process, etc.

Just to follow up on this point - an easy workaround for this is to create the accounts with random passwords, and then require the end-users to set their own passwords by triggering a password reset email for that user.

**Review by garyttierney — DISMISSED** [review]

**Comment by stephenmcconnachie** [comment]
@danielgrant Do you happen to know where the password settings are in Auth0, I can't find it! CC @rwhscott

**Comment by danielgrant** [comment]
> @danielgrant Do you happen to know where the password settings are in Auth0, I can't find it! CC @rwhscott

@stephenmcconnachie the password policies are configured on a per-connection basis, where a connection is essentially a pool of users. You can have multiple connections in each tenant. We only have one: `Username-Password-Connection`, you can access it under `Connections` -> `Database` - you'll then see the Password Policy tab.

Let me know if you want any changes applied to the policy - the Terraform serves as the single source of truth for all Auth0 configuration so any changes need to be applied to through it.

**Comment by stephenmcconnachie** [comment]
> @stephenmcconnachie the password policies are configured on a per-connection basis, where a connection is essentially a pool of users. You can have multiple connections in each tenant. We only have one: `Username-Password-Connection`, you can access it under `Connections` -> `Database` - you'll then see the Password Policy tab.
> 
> Let me know if you want any changes applied to the policy - the Terraform serves as the single source of truth for all Auth0 configuration so any changes need to be applied to through it.

Thank you that's great - we think that policy is fine, just wanted to explore the potential for forcing users to reset, we'll take a look

**Comment by rwhscott** [comment]
@stephenmcconnachie I just logged into Auth0 to take a look - password policy looks good to me.  Thanks @danielgrant, I think creating user accounts then sending a reset email should work just fine.

**Review by garyttierney — APPROVED** [review]

**Pull request merged**
